### ISSUE TITLE
561 is wrongly listed as prime

### ISSUE THREAD

**Issue by bmshukla** [Kakashiiiiy/AKS_PrimeTest#1] opened 2018-09-20 07:43 UTC
I have run the AKS_PrimeTest python code. It is showing 561 as prime which is wrong. 561%3 = 0
BM Shukla

**Comment by danaj** [comment] 2019-03-08 22:28
This is caused by the swapped range values in step3.

**Comment by benschlueter** [comment] 2019-03-13 13:31
I am not sure why, but now it should be fixed

**Closed as completed** 2019-12-27 20:41 UTC
